### PR TITLE
Refactoring attempt for the multi-counter

### PR DESCRIPTION
**Pull request by dmitriz**
@jayrbolton 

I have tried to simplify the inter-dependencies:

- The main new feature is that the list model only depends on the counter model rather than the counter component.

- Also the model dependencies are extracted as parameters from the views.

The main idea is to make the models reusable by removing any reference to the views.
The list model now only takes the single counter model.
I've thought that was the feature in your previous examples?

What do you think?

### CODE REVIEW

**Comment by jayrbolton** [comment]
On first glance I like it a lot. I'll play with it today

You're right that a recent update lost the total separation between model and views after making some other things more minimalistic. Your approach is interesting!

**Comment by dmitriz** [comment]
Cool, let me know then your thoughts.
I would really like to see some clear data-flow strategy.
What do you think of some more realistic examples like stripped down hackernews?

**Comment by efleming969** [comment]
A problem arises where all previous counter components loose their state.  I think it's because mapping over the steam (with counterView) and then apply the states cause handleChildren to wipe out all existing nodes

**Comment by dmitriz** [comment]
@efleming969 
Great catch, many thanks!
I can see that mapping stream over  the `counterView` is problematic as you point out,
because the view already takes streams, not values,
so it should not rerun on every stream update.

I was trying to follow the approach outlined in
https://github.com/uzujs/uzu/issues/6#issuecomment-304519136
where the models should take full care of the state
and the views should only passively attach to the models,
both as the state receiver, and pipe their event streams back into them.

Any ideas are greatly appreciated. 😄

**Comment by jayrbolton** [comment]
I played with it locally and now see what you both are talking about. counterView gets re-called whenever there is a new value in the `states` stream from line 53.

By the way, here is a "flimflam-style" approach, which initializes empty streams from the top:
https://gist.github.com/jayrbolton/8fa0780f5343f5ba07d5f5e97e81db28

There is a nice simplicity in that approach. You could also make it so that the counter model and the counterList model are separated. However, there is one main semantic drawback: by initializing empty streams, you dont know what they depend on, what type of data they will contain, and where they will be used. In contrast, the `stream.fromEvent` approach solves those problems nicely: you know exactly what the stream is derived from and what type of data is on the stream. However, it introduces its own problems.

I think the goal is to be able to dynamically initialize many child stream states from a child model without having to initialize the DOM view for each child. However, the event streams required by the child model are *derived from* the DOM view. 
```

**Comment by jayrbolton** [comment]
Here is another flimflam-style example with a separation between a single counter and many counters. This initializes event streams inside the models. It's almost object-oriented feeling
https://gist.github.com/jayrbolton/a65e92d2238329eb9ad2adbf4ecfbba3

**Comment by dmitriz** [comment]
@jayrbolton 
Thank you for your comments and the gists.

The basic question I am running into is -- who should own the data?
And this becomes a problem when you let the view instantiate its model.
I think it might be cleaner to run the model tree with their proxy streams first,
independently of the views:

```js
const proxyHandler = {
  get: function(target, name) {
    return name in target
      ? target[name]
      : target[name] = stream.create()
  }
}

const runModel = model => {
    const streamProxy = new Proxy({}, proxyHandler)
    return model(streamProxy)
}
```

That is nice trick inspired by how Turbine defines its `loop`, 
to replace the painful declarations

```js
  const [inc, dec, reset] = [stream.create(), stream.create(), stream.create()]
```

Now the models can be run, separately from the views,
 and make their live action streams available to the views.

I have concerns that the `modelView` function promotes tight coupling of model and view.
For instance, how would you handle several views using the same model running with the same state?
Like several independent controls operating on the same counter?

I would like to see more examples with several views subscribing to shared model tree,
dispatching their actions to different parts.
For instance, you view may have a local and global actions meant for different models.
That makes calling the model like `model(streams)` problematic,
you need something more flexible like the views dispatching into the model or model channel.

I see what you are saying that you may lose control over your data that way, as also @paldepind mentioned in https://github.com/paldepind/functional-frontend-architecture/issues/23#issuecomment-299294751. But there seems to be the flexibility price to pay, in that it gets harder to add an outside control to affect your model. And I don't see how this problem is currently addressed/solved in the Turbine design.

The more traditional approach with event callbacks piping into the model stream as in your gist, seems to give a very simple solution, of course, at the expense of losing some control:
```js
  h('button', {on: {click: counter.inc}}, '+1')
```
And you can limit your view to only dispatch into the model passed as argument.
So now you have to pass both source and receiver model to the view,
which brings us back to the basic [un-setup](https://github.com/dmitriz/un/blob/master/examples/active-counter/index.js#L7),
where I can see @paldepind unimpressed by reversing the flow back into the arguments 😄 

But in a way, it is similar to `modelView`, which also takes the view output and dispatches back to the model. So maybe it would be nice to make a more flexible glueing function that would selectively take view's output and dispatch into corresponding model, of which there might be several different ones. Even the same action might be good to dispatch into several models, rather than coupling them.

**Comment by dmitriz** [comment]
@jayrbolton 

Now that I read your past comments, the pure model decoupling was originally your own idea ;) https://github.com/uzujs/uzu/issues/2

But it does not seem to be enforced in your gists if I see it correctly, specifically I am worried about the views actively instantiating the models. Is that correct?

**Comment by jayrbolton** [comment]
Yes indeed, that's been my goal. This repo hasn't achieved a strong architectural pattern yet, I have just been playing with ideas so far. Right now the examples just represent a very minimalistic setup. I still haven't come upon anything totally satisfying.

I agree that a Proxy object might clean some things up. I actually hadn't seen the Proxy object before! Thanks for pointing that out.

One idea I've been thinking about would be to have a special `model` funciton that creates a special stream-state object with both input and output streams encapsulated

```js
// A plain/pure function from streams to streams
const keepCount = ({inc, dec, reset}) => 
  stream.scanMerge([
    [inc, R.add(1)]
  , [dec, R.add(-1)]
  , [reset, R.always(0)]
  ], 0)

// A model encapsulating stream input and output
// Pass in a function that takes an object of input streams and returns one or more output streams
const counter = model(keepCount)
counter.input // <-- this is a proxy object of streams
counter.input.inc(true)
counter.input.dec(true)
counter.input.dec(true)
counter.output() // -1

// simply use it in the view like
h('button', {on: {click: counter.input.inc}}, 'Increment')
h('p', {}, ['Total count is ', counter.output])
```

You could nest models within models and have a data tree totally independent from the view tree. It would also take care of circular dependencies. I want to code up a working example soon

In addition to having a model function (which I think could come from the stream library), we could keep the `fromEvent` function as well. That would offer a lot of flexibility.

**Comment by jayrbolton** [comment]
For reference, these two examples use the `stream.model` function which separates domain logic and view function:
https://github.com/uzujs/uzu/blob/master/examples/temp-converter-2.js
https://github.com/uzujs/uzu/blob/master/examples/multi-counter-2.js

I'm going to play with more examples from 7GUIs (particulary the CRUD and the spreadsheet examples) so I can continue to think about the architecture

**Pull request closed without merging**
