### PR TITLE
Implement the stream.model function with a multi-counter example

### PR DESCRIPTION
**Pull request by jayrbolton**
Hi @dmitriz and @efleming969: here is an idea for a `stream.model` function that allows for better logic/view separation, and also encapsulates both input and output streams into one object. The goal is to have a tree of models that is independent from the DOM tree.

Initially, I'm thinking this approach is very promising, and I like how tiny the implementation is. But I wonder if it is conceptually strange, or how the code reads to people (I will have to take a day or two to step away and look at it again).

The only disadvantage is that the stream binding is impure and you don't know where in the DOM your input streams will get bound, and you don't know what data will get pushed to them. I'd say, in my experience, this is more of a conceptual downside rather than a real-world downside

### CODE REVIEW

**Comment by dmitriz** [comment]
I like how it gets on the right track ;)

It still concerns me, that the pure `listCounter` calls the impure `stream.model` inside.
What about accumulating the pure update functions inside the parent update function:

```js
const listCounters = initial => ({add, rem}) =>
 +  stream.scanMerge([
 +    [add, cs => R.append(keepCount(0), cs)]
 +  , [rem, R.init]
 +  ], initial.map(c => keepCount(c)))
```
Then `stream.model` would instantiate the whole list model:
```js
const listModel = stream.model(listCounters)
```
Where the returned stream of arrays would be again mapped over the `stream.model`,
so that it would be applied recursively down the tree.

Basically, any time there is a node update function taking the stream object as input,
it should be instantiated by the proxy streams and each node 
would be replaced by the corresponding encapsulated model.
So in this case, the result of
```js
const list = stream.model(listCounters([1,2,3,4]))
```
would be the same but achieved with a single `stream.model` (or `stream.run`) invocation.

And the view separation is awesome!
The `counterView` has its local action only on its own model.
And the `counterListView` only acts on the `list`.

Not crucial, but maybe also simplify the view a bit? -

```js
const counterListView = list => [
     h('button', {on: {click: list.input.add}}, 'Add Counter')
    // here the fluent style looks a bit easier to read to me
   , list.output.map(arr => arr.map(counterView))
   , h('button', {on: {click: list.input.rem}}, 'Remove Counter')
]
```

And yes, it is impure ;(
But so is equally any Redux application.

The "purification" would involve outputting all the streams first,
after which you would need to call a binding impure utility function like 
`pipe(output, model)`, where you can select any `output` object (or part of it)
and pipe into any model (or several ones, via separate pipe calls).

Basically the same that the `modelView` or the `loop` functions do.

**Comment by dmitriz** [comment]
Then again, in React you compose component instances rather than their blueprints, so I might be wrong trying with pure update functions.

**Comment by jayrbolton** [comment]
Hmm, I'm not sure what would be involved in applying `stream.model` recursively down a tree, how messy that logic might be, and also I'm not sure it's really a problem to embed a model instance in there like I did. Maybe the important thing is that the domain model has been made totally independent of the view.

I think it's worth doing a few more examples to think about things

**Comment by dmitriz** [comment]
> Hmm, I'm not sure what would be involved in applying stream.model recursively down a tree, how messy that logic might be (especially if children in that tree may change with every stream update), and also I'm not sure it's really a problem to embed a model instance in there like I did.

Yes, sounds like the wrong idea. ;)

> Maybe the important thing is that the domain model has been made totally independent of the view.

Absolutely!

**Pull request merged**
